### ISSUE TITLE
Błędy podczas instalowania

### ISSUE THREAD

**Issue by AmberAbstracts** [Verlikylos/vMCShop#10]
Niewiem o co chodzi dlatego wyśle screeny. Może będziesz wiedział o co chodzi :)

![sklep squaremc j pl](https://user-images.githubusercontent.com/16156322/31053648-9a8a8b22-a6a2-11e7-8983-3bdc0ccd5ece.png)
---
--- Wersja Tekstowa ---
A PHP Error was encountered

Severity: Warning

Message: is_dir(): open_basedir restriction in effect. File(/var/lib/php5) is not within the allowed path(s): (/var/www/domains:/profiles:/virtual:/var/www/virtual:/usr/share/file:/usr/share/misc/magic:/tmp:/opt/php56u/lib/php:/dev)

Filename: drivers/Session_files_driver.php

Line Number: 134

Backtrace:

File: /profiles/i/if/ifr/ifritus/sklep.squaremc.j.pl/application/controllers/Home.php
Line: 17
Function: __construct

File: /profiles/i/if/ifr/ifritus/sklep.squaremc.j.pl/index.php
Line: 315
Function: require_once

---

A PHP Error was encountered

Severity: Warning

Message: mkdir(): open_basedir restriction in effect. File(/var/lib/php5) is not within the allowed path(s): (/var/www/domains:/profiles:/virtual:/var/www/virtual:/usr/share/file:/usr/share/misc/magic:/tmp:/opt/php56u/lib/php:/dev)

Filename: drivers/Session_files_driver.php

Line Number: 136

Backtrace:

File: /profiles/i/if/ifr/ifritus/sklep.squaremc.j.pl/application/controllers/Home.php
Line: 17
Function: __construct

File: /profiles/i/if/ifr/ifritus/sklep.squaremc.j.pl/index.php
Line: 315
Function: require_once

---

An uncaught Exception was encountered

Type: Exception

Message: Session: Configured save path '/var/lib/php5' is not a directory, doesn't exist or cannot be created.

Filename: /profiles/i/if/ifr/ifritus/sklep.squaremc.j.pl/system/libraries/Session/drivers/Session_files_driver.php

Line Number: 138

Backtrace:

File: /profiles/i/if/ifr/ifritus/sklep.squaremc.j.pl/application/controllers/Home.php
Line: 17
Function: __construct

File: /profiles/i/if/ifr/ifritus/sklep.squaremc.j.pl/index.php
Line: 315
Function: require_once

---

A PHP Error was encountered

Severity: Warning

Message: fopen(e5db1c9b96f37ba1c7c5ce47cba8a1e662d043cb): failed to open stream: Permission denied

Filename: drivers/Session_files_driver.php

Line Number: 172

Backtrace:

---

A PHP Error was encountered

Severity: Warning

Message: Unknown: Failed to write session data (user). Please verify that the current setting of session.save_path is correct (/var/lib/php5)

Filename: Unknown

Line Number: 0

Backtrace:

**Comment by Verlikylos** [comment]
https://github.com/Verlikylos/vMCShop/wiki/Znane-b%C5%82%C4%99dy-i-sposoby-ich-rozwi%C4%85zywania#b%C5%82%C4%85d-session-configured-save-path--is-not-a-directory-doesnt-exist-or-cannot-be-created
