### ISSUE TITLE
Błędy

### ISSUE THREAD

**Issue by 6594k** [Verlikylos/vMCShop#11]
A PHP Error was encountered

Severity: Warning

Message: is_dir(): open_basedir restriction in effect. File(/var/lib/php5/sessions) is not within the allowed path(s): (.:/home/zyrakio/:/tmp)

Filename: drivers/Session_files_driver.php

Line Number: 134

Backtrace:

File: /web1/web1/home/zyrakio/666957/application/controllers/Home.php
Line: 17
Function: __construct

File: /web1/web1/home/zyrakio/666957/index.php
Line: 315
Function: require_once
A PHP Error was encountered

Severity: Warning

Message: mkdir(): open_basedir restriction in effect. File(/var/lib/php5/sessions) is not within the allowed path(s): (.:/home/zyrakio/:/tmp)

Filename: drivers/Session_files_driver.php

Line Number: 136

Backtrace:

File: /web1/web1/home/zyrakio/666957/application/controllers/Home.php
Line: 17
Function: __construct

File: /web1/web1/home/zyrakio/666957/index.php
Line: 315
Function: require_once
An uncaught Exception was encountered

Type: Exception

Message: Session: Configured save path '/var/lib/php5/sessions' is not a directory, doesn't exist or cannot be created.

Filename: /web1/web1/home/zyrakio/666957/system/libraries/Session/drivers/Session_files_driver.php

Line Number: 138

Backtrace:

File: /web1/web1/home/zyrakio/666957/application/controllers/Home.php
Line: 17
Function: __construct

File: /web1/web1/home/zyrakio/666957/index.php
Line: 315
Function: require_once

**Comment by Verlikylos** [comment]
https://github.com/Verlikylos/vMCShop/wiki/Znane-b%C5%82%C4%99dy-i-sposoby-ich-rozwi%C4%85zywania#b%C5%82%C4%85d-session-configured-save-path--is-not-a-directory-doesnt-exist-or-cannot-be-created
