### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by JanekMaSkrypta** [Verlikylos/vMCShop#12]
Witam mam problem:

 

https://imgur.com/a/BJFhT

**Comment by JanekMaSkrypta** [comment]
Pytanie jest nastepujace czy dziala to na Enderchest? a jezeli tak to jak?

**Comment by Verlikylos** [comment]
Podałeś zły adres serwera MySQL. Polecam przeczytać dokładnie instrukcję instalacji.

Skrypt powinien działać na każdym serwerze WWW spełniającym podane wymagania.

**Comment by JanekMaSkrypta** [comment]
A dalbys rade mi pomoc z tym? ja bym ci dal Dostep do VPS i Enderchest ;d

**Comment by Verlikylos** [comment]
Wydaje mi się, że prościej się nie da. Przejrzyj sekcję z konfiguracją.
https://verlikylos.me/vmcshop-standard-instrukcja-instalacji-na-serwerze-www/
