### ISSUE TITLE
Paysafecard oraz PayPal

### ISSUE THREAD

**Issue by xDevoo** [Verlikylos/vMCShop#17]
Witam mam pytanko kiedy i czy wgl zostaną dodane metody płatności psc oraz paypal

**Comment by Verlikylos** [comment]
PSC dodaję tylko na zamówienie, a PayPal będzie wkrótce dostępny.

**Comment by xDevoo** [comment]
okej a jaki koszt psc?

**Comment by Verlikylos** [comment]
Zapraszam do kontaktu na Telgram/Facebook
