### ISSUE TITLE
Blad

### ISSUE THREAD

**Issue by arturek1666** [Verlikylos/vMCShop#20]
Wszystko zrobilem jak bylo pisane ale wciaz nie moge zrozumiec oco chodzi z tym bledem jakies pomysly:
Sprawdzalem i wymagania sa spelniane. 
`A PHP Error was encountered
Severity: Warning

Message: mkdir(): Invalid path

Filename: drivers/Session_files_driver.php

Line Number: 136

Backtrace:

File: /usr/home/hostplay/domains/fanimc.pl/public_html/application/controllers/Home.php
Line: 16
Function: __construct

File: /usr/home/hostplay/domains/fanimc.pl/public_html/index.php
Line: 315
Function: require_once`

**Comment by Verlikylos** [comment]
https://github.com/Verlikylos/vMCShop/wiki/Znane-b%C5%82%C4%99dy-i-sposoby-ich-rozwi%C4%85zywania#b%C5%82%C4%85d-session-configured-save-path--is-not-a-directory-doesnt-exist-or-cannot-be-created
