### ISSUE TITLE
Błąd w statusach serwerów.

### ISSUE THREAD

**Issue by SzymoonDev** [Verlikylos/vMCShop#6]
Dodałem serwer, status działa. Ładnie pokazuje graczy,
Problem jest wtedy, gdy serwer się włącza, a ktoś odświeży w tym czasie stronę. Wtedy pokazuje się błąd przy danym serwerze:
https://scr.hu/RYwBLr

**Comment by Verlikylos** [comment]
Dzięki. Myślę, że w niedziele wleci update z fixami.
